import Head from "next/head";
import { Button } from "@common/ui";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-wid1th, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>asdddddddddddd</div>
      </main>
    </>
  );
}
