plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  swiper@*:
    dependencies:
      '@types/react': '^17'
      react: '^17'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - gnu
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.3.0.cjs
