version: '3'

services:
  jurumarble:
    container_name: jurumarble
    build:
      context: .
      dockerfile: ../../apps/jurumarble/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
      - /app/.next
    command: sh -c "yarn workspace @monorepo/jurumarble dev"
